# 课程1.5---Numpy数据的输入与输出
## Numpy读取/写入数组数据，文本数据

In [1]:
# 存储数组数据 .npy文件

import numpy as np
import os
os.chdir(r"D:\Python练习")

ar = np.random.rand(5,5)
print(ar)
np.save("arraydata.npy",ar)
# 也可以直接 np.save(r"D:\Python练习\arraydata.npy", ar)

[[0.13389287 0.964937   0.21994744 0.02316549 0.91121663]
 [0.60693404 0.46538374 0.68338372 0.3042743  0.94794604]
 [0.57445204 0.96189776 0.04712687 0.14613759 0.01298376]
 [0.97465597 0.25768499 0.95910334 0.66669867 0.22205536]
 [0.84205466 0.64499971 0.78520505 0.87420594 0.7727194 ]]


In [2]:
# 读取数组文件 .npy文件

ar_load = np.load("arraydata.npy")
print(ar_load)
# 也可以直接np.load(r"# 存储数组数据 .npy文件）


[[0.13389287 0.964937   0.21994744 0.02316549 0.91121663]
 [0.60693404 0.46538374 0.68338372 0.3042743  0.94794604]
 [0.57445204 0.96189776 0.04712687 0.14613759 0.01298376]
 [0.97465597 0.25768499 0.95910334 0.66669867 0.22205536]
 [0.84205466 0.64499971 0.78520505 0.87420594 0.7727194 ]]


In [3]:
# 存储/读取文本文件

ar = np.random.rand(5,5)
np.savetxt("array.txt",ar,delimiter = ',')
# np.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ')：存储为文本txt文件

ar_loadtxt = np.loadtxt('array.txt', delimiter=',')
print(ar_loadtxt)
# 也可以直接 np.loadtxt(r"D:\Python练习\arraydata.txt")

[[0.84976815 0.05472687 0.46660554 0.50229243 0.07287162]
 [0.54284133 0.03102612 0.42999545 0.55241157 0.81341422]
 [0.00574233 0.0480327  0.29999644 0.07674653 0.28178927]
 [0.60563717 0.87023471 0.44676801 0.50214281 0.6035047 ]
 [0.26137627 0.69369219 0.12449053 0.11795134 0.71186916]]


In [3]:
import pickle

保存一切对象（变量、对象、模型、数据）

a = [1,3,4]
b = np.arange(16)
c = "1234"
model

with open("pk.tmp","wb") as f:
    pickle.dump([a,b,c,model],f)

with open("pk.tmp","rb") as f:
    a,b,c,model = pickle.load(f)

In [6]:
??pickle.dump

Signature:
pickle.dump(
    obj,
    file,
    protocol=None,
    *,
    fix_imports=True,
    buffer_callback=None,
)
Docstring:
Write a pickled representation of obj to the open file object file.

This is equivalent to ``Pickler(file, protocol).dump(obj)``, but may
be more efficient.

The optional *protocol* argument tells the pickler to use the given
protocol; supported protocols are 0, 1, 2, 3, 4 and 5.  The default
protocol is 4. It was introduced in Python 3.4, and is incompatible
with previous versions.

Specifying a negative protocol version selects the highest protocol
version supported.  The higher the protocol used, the more recent the
version of Python needed to read the pickle produced.

The *file* argument must have a write() method that accepts a single
bytes argument.  It can thus be a file object opened for binary
writing, an io.BytesIO instance, or any other custom object that meets
this interface.

If *fix_imports* is True and protocol is less than 3, pickle will try